### PR TITLE
Listing WOLF token

### PR DESCRIPTION
**Pull request by dhasan**
Listing WOLF token

### CODE REVIEW

**Comment by Gmtenchi777** [comment]
@Felix0xTHUNDER check this @Maneshjl @anggapurba @rogerhsu-tt

**Comment by dhasan** [comment]
Fee: https://viewblock.io/thundercore/tx/0x7b4d5e154f5e73f1890a0dbc8234ed11975ffae62d3c8af2ba8cad1277539e47

**Review by Gmtenchi777 — APPROVED** [review]
Check @Felix0xTHUNDER Stake site looks like coin has good liquidity dapp runs perfectly on TT hub no bugs for now Suply of coin and fixed in 2000

**Review by Joaozim133 — APPROVED** [review]

**Comment by xandaopizzas** [comment]
good liquidity , approved by employees

**Comment by dhasan** [comment]
Thanks, @Felix0xTHUNDER @rogerhsu-tt We have three pull requests, one of them is almost one month old, I would like to know when token listing, staking and game will be merged and listed on TT wallet, we followed all requirements for dapp submission and token listing.

**Comment by dhasan** [comment]
If this blockchain is created for the purpose of earning money of a small group of people from gambling games somehow connected to admins, receiving cuts or payroll from them just say it and don’t waste our time and money, otherwise I don’t understand this stubbornness

**Comment by rogerhsu-tt** [comment]
> If this blockchain is created for the purpose of earning money of a small group of people from gambling games somehow connected to admins, receiving cuts or payroll from them just say it and don’t waste our time and money, otherwise I don’t understand this stubbornness

What's the actual use case of this token except stake and earn, and the tokenomics/roadmap of this token?

**Comment by Gmtenchi777** [comment]
Certainly listen to the TT admins and everything will be fine with your frog friend Wolf games pokerdice

**Comment by dhasan** [comment]
security token

**Comment by Gmtenchi777** [comment]
@rogerhsu-tt You helped me a lot in the beginning to understand thundercore I'm grateful I'm Tenchi Masaki from thundercore Brasil Farms stacks

**Comment by dhasan** [comment]
Initial token supply is 2000wolf with 470k TT as of now. In long term we will maintain slow and sustainable grow of capitalisation. In case of sharp up moves new tokens will be minted and additional liquidity be provided, In case of sharp drops liquidity will be pulled and tokens will be burned to protect investors.

**Comment by dhasan** [comment]
https://github.com/thundercore/token-list here is nothing about roadmap?

**Comment by rogerhsu-tt** [comment]
> https://github.com/thundercore/token-list in these requirements for token listing is nothing about roadmap???

Roadmap is not mandatory if the token use case is obvious. To be straight, there were a few tokens listed on TT Wallet and TTSwap which do not have actual use cases and they rug users' assets not long afterwards. To protect the users in ThunderCore ecosystem, we have made the token listing validating more strict afterwards.

**Comment by dhasan** [comment]
Piece of paper can't protect users from rug pull. As you can se we not pulling liquidity even now when the communication between us and tt admins hit the bottom. there is 50k difference between initial liquidity and current. Not listing the token without reasonable "excuses" would jeopardise our effort and peoples money.

**Comment by rogerhsu-tt** [comment]
> Piece of paper can't protect users from rug pull. As you can se we not pulling liquidity even now when the communication between us and tt admins hit the bottom, because we believe that users shouldn't get punished because of greediness of few tt admins like the frog :) there is 50k difference between initial liquidity and current. Not listing the token without reasonable "excuses" would jeopardise our effort and peoples money.
> 
> Also isn't it obvious that you can stake the token?
> 
> Currently there are tokens listed on ttswsp without functional web page, so you have to come up with different excuse 😀

I don't intend to argue with you. The tokens listed on ttswap without functional web pages were the mistakes we made. Keeping them there is just for the existing holders a place to trade, nothing more. We may take them down anytime when it comes to a proper timing.

If the stake and earn is the "only" usage of a token, it's not sufficient for our standard now. Try to make it cooperate with your other DApps. Besides, since there are already dozens of dice games in ThunderCore ecosystem, please put some effort to improve the quality of your dice DApps as well, such as better UI/UX, more interesting mechanism, etc.

**Comment by dhasan** [comment]
I will escalate this, you openly refuse to provide equal opportunity for all developers, protecting the existing dapps. And the motivation to this is that you are corrupt, and getting cuts. What kind of admin wouldn't welcome competition?

**Comment by dhasan** [comment]
What kind of admin approve dapps without contract verification? 
All dapps listed on tt wallet are unapproved. 
You stealing peoples money, with scam gambling games.
The only verified games are ours!

**Comment by Felix0xTHUNDER** [comment]
Ok, let's focus more on token listing.
In general, if this token is related to the dapp, we usually list the dapp first and then go onto listing their tokens.
I would love to see you grow your community first and then apply for listing as your community's adoption rate of your token plays a vital part in the token listing process, thank you.

**Comment by dhasan** [comment]
😂😂

**Pull request closed without merging**
