### PR TITLE
Add 3Star Token

### PR DESCRIPTION
**Pull request by sasakevin**

### CODE REVIEW

**Comment by sasakevin** [comment]
listing fee: 0x95a5aec9936fceaa29627dfce422e726908dceb588184946171fc47b838717e5

**Comment by Felix0xTHUNDER** [comment]
Thanks, the team will review and process.

**Comment by vandoe** [comment]
> _ No description provided. _

Nice

**Review by Minthu34 — APPROVED** [review]

**Review by Minthu34 — COMMENTED** [review]
0xA3E8DB20c73cfB75dC2a5929A38C62Eaef515106

**Comment by Felix0xTHUNDER** [comment]
The website is down.

**Pull request closed without merging**
