### PR TITLE
Add Dolphin Token

### PR DESCRIPTION
**Pull request by dan-official**

### CODE REVIEW

**Comment by dan-official** [comment]
tx for listing fee: 0x2586d0937c12f03af5fd3c3d4710280b0bbb272901af372b26c9f7ddde0f10de

**Comment by Gmtenchi777** [comment]
Dev token Guess dolphin when dividends will be released

**Comment by Gmtenchi777** [comment]
This contract is sure to have great liquidity

**Comment by Gmtenchi777** [comment]
The supply is only 5000 coins or there will be more than that

**Comment by Gmtenchi777** [comment]
How will the dividends be, it will be necessary to use lp or not

**Review by Gmtenchi777 — APPROVED** [review]
Nice New Guess token

**Comment by Felix0xTHUNDER** [comment]
@dan-official Hi, please check the mail. Thanks.

**Review by Felix0xTHUNDER — APPROVED** [review]

**Pull request merged**
