### PR TITLE
Add token MoneyThunder

### PR DESCRIPTION
**Pull request by MoneyThunder**
src/thundercore.json

{ "name": "youtube", "url": "https://youtube.com/channel/UC-K53dxaCK59yZBTGkNaYqg" }
      ],
      "tags": []
    },
    {
      "address": "0xbD708f451215f9De0b4dCa9eAB2f19820aEbbeC2",
      "symbol": "MT",
      "name": "MoneyThunder",
      "decimals": 18,
      "description": "MT Token is used for payment of tasks in different social networks and to earn profits in TT more easily and passively.",
      "ttswap_exchange": "0x6a009e3a5C1dE8Bec4712D7b470437D7E24842Ab",
      "website": "https://Cryptomt.wordpress.com/",
      "socials": [{ "name": "email", "url": "MoneyThundermt@gmail.com" }],
      "tags": []
    }
  ]
}

### CODE REVIEW

**Comment by rogerhsu-tt** [comment]
@MoneyThunder 
1. Please correctly update the files, there is no info of MT token in the repo files.
2. What's the usage of this token?

**Review by rogerhsu-tt — CHANGES_REQUESTED** [review]
Please correctly update the files, there is no info of MT token in the repo files.

**Comment by TTcaketoken** [comment]
Add token TTCAKE

Address:0xB18cf4Fd20f14f62ca6622451676abF190B47726

Token name: pancakeswap token
Symbol: Cake
Decimals:18

T.me/caketokentt

mohammadaminamere886@gmail.com
http://ttcake.wotor.net/

**Comment by MoneyThunder** [comment]
logo6_20_214635

**Review by rogerhsu-tt — CHANGES_REQUESTED** [review]
Please correctly update the files in the repo, not write on the PR comment.

**Pull request closed without merging**
